
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.net.UnknownHostException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Satyam
 */
public class search extends javax.swing.JFrame {

    /**
     * Creates new form search
     */
    private  Socket socket= null; 
	private  DataInputStream input = null; 
	private  DataOutputStream out= null; 
        String username;
        String password;
    public search() {
        initComponents();
        //jTextField1.setText(rec[0]);
        //jTextField6.setText(rec[1]);
        //jTextField3.setText(rec[2]);
        //jTextField5.setText(rec[3]);
        //jTextField4.setText(rec[4]);
        //jTextField2.setText(rec[5]);
    }
   
    public search(String[] rec)
    {
      initComponents();
        jTextField1.setText(rec[0]);
        jTextField6.setText(rec[1]);
        jTextField3.setText(rec[2]);
        jTextField5.setText(rec[3]);
        jTextField4.setText(rec[4]);
        jTextField2.setText(rec[5]); 
        jLabel7.setText(rec[6]);
        username=rec[7];
        password=rec[8];
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(null);

        jButton2.setText("CLOSE");
        jButton2.setMinimumSize(new java.awt.Dimension(70, 40));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(240, 10, 73, 20);

        jLabel1.setText("type");
        jLabel1.setMaximumSize(new java.awt.Dimension(30, 20));
        jLabel1.setMinimumSize(new java.awt.Dimension(30, 20));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 58, 84, 27);

        jTextField1.setMinimumSize(new java.awt.Dimension(10, 30));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(160, 50, 140, 30);

        jLabel2.setText("name");
        jLabel2.setMaximumSize(new java.awt.Dimension(40, 30));
        jLabel2.setMinimumSize(new java.awt.Dimension(40, 30));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 100, 84, 22);

        jLabel3.setText("cost");
        jLabel3.setMaximumSize(new java.awt.Dimension(40, 30));
        jLabel3.setMinimumSize(new java.awt.Dimension(40, 30));
        jLabel3.setPreferredSize(new java.awt.Dimension(30, 20));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 140, 30, 20);

        jTextField2.setMinimumSize(new java.awt.Dimension(10, 30));
        getContentPane().add(jTextField2);
        jTextField2.setBounds(160, 130, 150, 30);

        jLabel4.setText("manufactured date");
        jLabel4.setMinimumSize(new java.awt.Dimension(100, 30));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 180, 92, 14);

        jTextField3.setMinimumSize(new java.awt.Dimension(10, 30));
        getContentPane().add(jTextField3);
        jTextField3.setBounds(160, 170, 150, 30);

        jLabel5.setText("Expiry date");
        jLabel5.setMinimumSize(new java.awt.Dimension(55, 30));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 220, 55, 14);

        jLabel6.setText("discount");
        jLabel6.setMinimumSize(new java.awt.Dimension(50, 30));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 270, 77, 14);

        jTextField4.setMinimumSize(new java.awt.Dimension(10, 30));
        getContentPane().add(jTextField4);
        jTextField4.setBounds(170, 260, 150, 30);

        jTextField5.setMinimumSize(new java.awt.Dimension(10, 30));
        getContentPane().add(jTextField5);
        jTextField5.setBounds(160, 210, 150, 30);

        jTextField6.setMinimumSize(new java.awt.Dimension(10, 30));
        getContentPane().add(jTextField6);
        jTextField6.setBounds(160, 90, 140, 30);

        jButton3.setText("BUY");
        jButton3.setMaximumSize(new java.awt.Dimension(70, 43));
        jButton3.setMinimumSize(new java.awt.Dimension(70, 43));
        jButton3.setPreferredSize(new java.awt.Dimension(70, 43));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(60, 330, 70, 43);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(240, 324, 130, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String send="";
        send="buy"+" ";
        send+=jTextField1.getText()+" ";
        send+=jTextField6.getText()+" ";
        send+=username+" ";
        send+=password;
                try
		{ 
			socket = new Socket("127.0.0.1", 5000); 
			System.out.println("Connected");
//                        
//                        Scanner sc = new Scanner(System.in);
//                        String str = sc.nextLine();

			// takes input from terminal 
			input = new DataInputStream(socket.getInputStream()); 

			// sends output to the socket 
			out = new DataOutputStream(socket.getOutputStream()); 
		} 
		catch(UnknownHostException u) 
		{ 
			System.out.println(u); 
		} 
		catch(IOException i) 
		{ 
			System.out.println(i); 
		} 

		// string to read message from input 
		String line = ""; 

		// keep reading until "Over" is input 
		//while (!line.equals("Over")) 
		{ 
                    
			try
			{ 
                            
				//line = input.readLine(); 
                                
				out.writeUTF(send); 
                                line=input.readUTF();
                                String[] words=line.split("\\s+");
                                if(words[0].equals("iteam"))
                                {
                                   JOptionPane.showMessageDialog(null,line);
                                    
                                }
                                else
                                {
                                    JOptionPane.showMessageDialog(null, line);
                                }
			} 
			catch(IOException i) 
			{ 
				System.out.println(i); 
			} 
		} 

		// close the connection 
		try
		{ 
			input.close(); 
			out.close(); 
			socket.close(); 
		} 
		catch(IOException i) 
		{ 
			System.out.println(i); 
		}
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new search().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
